@Vms.Api_HostAddress = https://localhost:7082

POST {{Vms.Api_HostAddress}}/todoitems
Content-Type: application/json

{
  "name":"walk dog",
  "isComplete":false
}
###

GET {{Vms.Api_HostAddress}}/todoitems

###

GET {{Vms.Api_HostAddress}}/todoitems/1

###

GET {{Vms.Api_HostAddress}}/todoitems/complete

###

PUT {{Vms.Api_HostAddress}}/todoitems/1
Content-Type: application/json

{
  "id": 1,
  "name": "walk dog",
  "isComplete": true
}

###

DELETE {{Vms.Api_HostAddress}}/todoitems/1

###
