// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Vms.Data.Models;

public partial class Company
{
    public string Code { get; set; } = null!;

    public string Name { get; set; } = null!;

    public virtual ICollection<Customer> Customer { get; set; } = new List<Customer>();

    public virtual ICollection<Fleet> Fleet { get; set; } = new List<Fleet>();

    public virtual ICollection<Network> Network { get; set; } = new List<Network>();

    public virtual ICollection<Vehicle> Vehicle { get; set; } = new List<Vehicle>();
}