// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Vms.Data.Models;

public partial class Customer
{
    public string CompanyCode { get; set; } = null!;

    public string Code { get; set; } = null!;

    public string Name { get; set; } = null!;

    public virtual Company CompanyCodeNavigation { get; set; } = null!;

    public virtual ICollection<CustomerNetwork> CustomerNetwork { get; set; } = new List<CustomerNetwork>();

    public virtual ICollection<Vehicle> Vehicle { get; set; } = new List<Vehicle>();
}