// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Vms.Data.Models;

public partial class CustomerNetwork
{
    public string CustomerCode { get; set; } = null!;

    public string NetworkCode { get; set; } = null!;

    public string CompanyCode { get; set; } = null!;

    public virtual Customer C { get; set; } = null!;

    public virtual Network Network { get; set; } = null!;
}