// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Vms.Data.Models;

public partial class DriverVehicles
{
    public string EmailAddress { get; set; } = null!;

    public Guid VehicleId { get; set; }

    public virtual Driver EmailAddressNavigation { get; set; } = null!;

    public virtual Vehicle Vehicle { get; set; } = null!;
}