// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using NetTopologySuite.Geometries;

namespace Vms.Data.Models;

public partial class Driver
{
    public string EmailAddress { get; set; } = null!;

    public string? Salutation { get; set; }

    public string? FirstName { get; set; }

    public string? MiddleNames { get; set; }

    public string LastName { get; set; } = null!;

    public string MobileNumber { get; set; } = null!;

    public Geometry HomeLocation { get; set; } = null!;

    public virtual DriverVehicles? DriverVehicles { get; set; }
}