// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Vms.Data.Models;

public partial class Fleet
{
    public string CompanyCode { get; set; } = null!;

    public string Code { get; set; } = null!;

    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public virtual Company CompanyCodeNavigation { get; set; } = null!;

    public virtual ICollection<FleetNetwork> FleetNetwork { get; set; } = new List<FleetNetwork>();

    public virtual ICollection<Vehicle> Vehicle { get; set; } = new List<Vehicle>();
}