// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Vms.Data.Models;

public partial class ServiceBookingSupplier
{
    public Guid ServiceBookingId { get; set; }

    public string SupplierCode { get; set; } = null!;

    public virtual ServiceBooking ServiceBooking { get; set; } = null!;

    public virtual Supplier SupplierCodeNavigation { get; set; } = null!;
}