// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Vms.Data.Models;

public partial class ServiceBooking
{
    public Guid Id { get; set; }

    public Guid VehicleId { get; set; }

    public DateOnly PreferredDate1 { get; set; }

    public DateOnly? PreferredDate2 { get; set; }

    public DateOnly? PreferredDate3 { get; set; }

    public DateOnly? MotDue { get; set; }

    public int Status { get; set; }

    public virtual ServiceBookingSupplier? ServiceBookingSupplier { get; set; }

    public virtual Vehicle Vehicle { get; set; } = null!;
}