// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using NetTopologySuite.Geometries;

namespace Vms.Data.Models;

public partial class Vehicle
{
    public Guid Id { get; set; }

    public string CompanyCode { get; set; } = null!;

    public string Make { get; set; } = null!;

    public string Model { get; set; } = null!;

    public string? ChassisNumber { get; set; }

    public DateOnly DateFirstRegistered { get; set; }

    public string AddressStreet { get; set; } = null!;

    public string AddressLocality { get; set; } = null!;

    public string AddressTown { get; set; } = null!;

    public string AddressPostcode { get; set; } = null!;

    public Geometry AddressLocation { get; set; } = null!;

    public string? CustomerCode { get; set; }

    public string? FleetCode { get; set; }

    public virtual Customer? C { get; set; }

    public virtual Company CompanyCodeNavigation { get; set; } = null!;

    public virtual ICollection<DriverVehicles> DriverVehicles { get; set; } = new List<DriverVehicles>();

    public virtual Fleet? Fleet { get; set; }

    public virtual VehicleModel M { get; set; } = null!;

    public virtual ICollection<ServiceBooking> ServiceBooking { get; set; } = new List<ServiceBooking>();

    public virtual VehicleMot? VehicleMot { get; set; }

    public virtual VehicleVrm? VehicleVrm { get; set; }
}