// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Vms.Data.Models;

public partial class VehicleModel
{
    public string Make { get; set; } = null!;

    public string Model { get; set; } = null!;

    public virtual VehicleMake MakeNavigation { get; set; } = null!;

    public virtual ICollection<Vehicle> Vehicle { get; set; } = new List<Vehicle>();
}