// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Vms.Data.Models;

public partial class VehicleMake
{
    public string Make { get; set; } = null!;

    public virtual ICollection<VehicleModel> VehicleModel { get; set; } = new List<VehicleModel>();

    public virtual ICollection<Supplier> SupplierCode { get; set; } = new List<Supplier>();
}