@Scrum.Api_HostAddress = https://localhost:7195
@ProductId = 98e0791c-9755-48d9-a163-f95f4e355b7b

GET {{Scrum.Api_HostAddress}}/api/product

###

POST {{Scrum.Api_HostAddress}}/api/product/{{ProductId}}
Content-Type: application/json

{
  "Name": "123"
}

###

POST {{Scrum.Api_HostAddress}}/api/product
Content-Type: application/json

{
  "name": "a test from the api2"
}

###

GET {{Scrum.Api_HostAddress}}/api/product

###

GET {{Scrum.Api_HostAddress}}/api/product

###
