// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Vms.Domain.Infrastructure;

#nullable disable

namespace Vms.Domain.Infrastructure.VmsDb
{
    [DbContext(typeof(VmsDbContext))]
    [Migration("20230731153153_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vms.Domain.Entity.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("ActivityLog", (string)null);
                });

            modelBuilder.Entity("Vms.Domain.Entity.Company", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Code");

                    b.ToTable("Company", (string)null);
                });

            modelBuilder.Entity("Vms.Domain.Entity.Customer", b =>
                {
                    b.Property<string>("CompanyCode")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.HasKey("CompanyCode", "Code");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("Vms.Domain.Entity.CustomerNetwork", b =>
                {
                    b.Property<string>("CompanyCode")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("NetworkCode")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("CustomerCode")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.HasKey("CompanyCode", "NetworkCode", "CustomerCode");

                    b.HasIndex("CompanyCode", "CustomerCode");

                    b.ToTable("CustomerNetwork", (string)null);
                });

            modelBuilder.Entity("Vms.Domain.Entity.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<Geometry>("HomeLocation")
                        .IsRequired()
                        .HasColumnType("geography");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MiddleNames")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Salutation")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.HasAlternateKey("CompanyCode", "EmailAddress");

                    b.ToTable("Driver", (string)null);
                });

            modelBuilder.Entity("Vms.Domain.Entity.DriverVehicle", b =>
                {
                    b.Property<string>("CompanyCode")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompanyCode", "DriverId", "VehicleId");

                    b.HasIndex("CompanyCode", "VehicleId");

                    b.ToTable("DriverVehicles");
                });

            modelBuilder.Entity("Vms.Domain.Entity.Email", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Recipients")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Emails", "System");
                });

            modelBuilder.Entity("Vms.Domain.Entity.Fleet", b =>
                {
                    b.Property<string>("CompanyCode")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.HasKey("CompanyCode", "Code");

                    b.ToTable("Fleet", (string)null);
                });

            modelBuilder.Entity("Vms.Domain.Entity.FleetNetwork", b =>
                {
                    b.Property<string>("CompanyCode")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("FleetCode")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("NetworkCode")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.HasKey("CompanyCode", "FleetCode", "NetworkCode");

                    b.HasIndex("CompanyCode", "NetworkCode");

                    b.ToTable("FleetNetwork", (string)null);
                });

            modelBuilder.Entity("Vms.Domain.Entity.Login", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Logins", "ClientApp");
                });

            modelBuilder.Entity("Vms.Domain.Entity.Network", b =>
                {
                    b.Property<string>("CompanyCode")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.HasKey("CompanyCode", "Code");

                    b.ToTable("Network", (string)null);
                });

            modelBuilder.Entity("Vms.Domain.Entity.NetworkSupplier", b =>
                {
                    b.Property<string>("CompanyCode")
                        .HasColumnType("nchar(10)");

                    b.Property<string>("NetworkCode")
                        .HasColumnType("nchar(10)");

                    b.Property<string>("SupplierCode")
                        .HasColumnType("varchar(8)");

                    b.HasKey("CompanyCode", "NetworkCode", "SupplierCode");

                    b.HasIndex("SupplierCode");

                    b.ToTable("NetworkSupplier", (string)null);
                });

            modelBuilder.Entity("Vms.Domain.Entity.RescheduleReason", b =>
                {
                    b.Property<string>("CompanyCode")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.HasKey("CompanyCode", "Code");

                    b.ToTable("RescheduleReasons", (string)null);
                });

            modelBuilder.Entity("Vms.Domain.Entity.ServiceBookingEntity.ConfirmBookedRefusalReason", b =>
                {
                    b.Property<string>("CompanyCode")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.HasKey("CompanyCode", "Code");

                    b.ToTable("ConfirmBookedRefusalReasons", (string)null);
                });

            modelBuilder.Entity("Vms.Domain.Entity.ServiceBookingEntity.Follower", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentId", "UserId");

                    b.ToTable("Followers", (string)null);
                });

            modelBuilder.Entity("Vms.Domain.Entity.ServiceBookingEntity.MotEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasColumnType("nchar(10)");

                    b.Property<DateOnly>("Due")
                        .HasColumnType("date");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ServiceBookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ValidFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidFrom");

                    b.Property<DateTime>("ValidTo")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidTo");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId", "IsCurrent")
                        .IsUnique()
                        .HasFilter("IsCurrent = 1");

                    b.HasIndex("CompanyCode", "VehicleId", "ServiceBookingId")
                        .IsUnique()
                        .HasFilter("[ServiceBookingId] IS NOT NULL");

                    b.ToTable("MotEvent", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("MotEventHistory");
                                ttb
                                    .HasPeriodStart("ValidFrom")
                                    .HasColumnName("ValidFrom");
                                ttb
                                    .HasPeriodEnd("ValidTo")
                                    .HasColumnName("ValidTo");
                            }));
                });

            modelBuilder.Entity("Vms.Domain.Entity.ServiceBookingEntity.NonArrivalReason", b =>
                {
                    b.Property<string>("CompanyCode")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.HasKey("CompanyCode", "Code");

                    b.ToTable("NonArrivalReasons", (string)null);
                });

            modelBuilder.Entity("Vms.Domain.Entity.ServiceBookingEntity.NotCompleteReason", b =>
                {
                    b.Property<string>("CompanyCode")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.HasKey("CompanyCode", "Code");

                    b.ToTable("NotCompleteReasons", (string)null);
                });

            modelBuilder.Entity("Vms.Domain.Entity.ServiceBookingEntity.RefusalReason", b =>
                {
                    b.Property<string>("CompanyCode")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.HasKey("CompanyCode", "Code");

                    b.ToTable("RefusalReasons", (string)null);
                });

            modelBuilder.Entity("Vms.Domain.Entity.ServiceBookingEntity.ServiceBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssignedToUserId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("BookedDate")
                        .HasColumnType("date");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("CreatedUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("EstimatedCompletion")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("MotDue")
                        .HasColumnType("date");

                    b.Property<Guid?>("MotEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OwnerUserId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("PreferredDate1")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("PreferredDate2")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("PreferredDate3")
                        .HasColumnType("date");

                    b.Property<DateTime?>("RescheduleTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceLevel")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SupplierCode")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("CreatedUserId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("SupplierCode");

                    b.ToTable("ServiceBooking", (string)null);
                });

            modelBuilder.Entity("Vms.Domain.Entity.ServiceBookingEntity.ServiceBookingLock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Granted")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ServiceBookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceBookingId")
                        .IsUnique();

                    b.ToTable("ServiceBookingLock", (string)null);
                });

            modelBuilder.Entity("Vms.Domain.Entity.Supplier", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<bool>("IsIndependent")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Code");

                    b.ToTable("Supplier", (string)null);
                });

            modelBuilder.Entity("Vms.Domain.Entity.TaskLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Log")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TaskLogs", null, t =>
                        {
                            t.HasCheckConstraint("Log record should be formatted as JSON", "ISJSON(log)=1");
                        });
                });

            modelBuilder.Entity("Vms.Domain.Entity.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users", "ClientApp");
                });

            modelBuilder.Entity("Vms.Domain.Entity.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChassisNumber")
                        .HasMaxLength(18)
                        .IsUnicode(false)
                        .HasColumnType("varchar(18)");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("CustomerCode")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<DateOnly>("DateFirstRegistered")
                        .HasColumnType("date");

                    b.Property<string>("FleetCode")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyCode", "CustomerCode");

                    b.HasIndex("CompanyCode", "FleetCode");

                    b.HasIndex("Make", "Model");

                    b.ToTable("Vehicle", (string)null);
                });

            modelBuilder.Entity("Vms.Domain.Entity.VehicleMake", b =>
                {
                    b.Property<string>("Make")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Make")
                        .HasName("PK_Make");

                    b.ToTable("VehicleMake", (string)null);
                });

            modelBuilder.Entity("Vms.Domain.Entity.VehicleModel", b =>
                {
                    b.Property<string>("Make")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Make", "Model")
                        .HasName("PK_Model");

                    b.ToTable("VehicleModel", (string)null);
                });

            modelBuilder.Entity("Vms.Domain.Entity.Customer", b =>
                {
                    b.HasOne("Vms.Domain.Entity.Company", "CompanyCodeNavigation")
                        .WithMany("Customers")
                        .HasForeignKey("CompanyCode")
                        .IsRequired()
                        .HasConstraintName("FK_Customer_Company");

                    b.Navigation("CompanyCodeNavigation");
                });

            modelBuilder.Entity("Vms.Domain.Entity.CustomerNetwork", b =>
                {
                    b.HasOne("Vms.Domain.Entity.Customer", "C")
                        .WithMany("CustomerNetworks")
                        .HasForeignKey("CompanyCode", "CustomerCode")
                        .IsRequired()
                        .HasConstraintName("FK_CustomerNetwork_Customer");

                    b.HasOne("Vms.Domain.Entity.Network", "Network")
                        .WithMany("CustomerNetworks")
                        .HasForeignKey("CompanyCode", "NetworkCode")
                        .IsRequired()
                        .HasConstraintName("FK_CustomerNetwork_Network");

                    b.Navigation("C");

                    b.Navigation("Network");
                });

            modelBuilder.Entity("Vms.Domain.Entity.Driver", b =>
                {
                    b.HasOne("Vms.Domain.Entity.Company", "CompanyCodeNavigation")
                        .WithMany("Drivers")
                        .HasForeignKey("CompanyCode")
                        .IsRequired()
                        .HasConstraintName("FK_Driver_Company");

                    b.Navigation("CompanyCodeNavigation");
                });

            modelBuilder.Entity("Vms.Domain.Entity.DriverVehicle", b =>
                {
                    b.HasOne("Vms.Domain.Entity.Driver", "Driver")
                        .WithMany("DriverVehicles")
                        .HasForeignKey("CompanyCode", "DriverId")
                        .HasPrincipalKey("CompanyCode", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DriverVehicles_Driver");

                    b.HasOne("Vms.Domain.Entity.Vehicle", "Vehicle")
                        .WithMany("DriverVehicles")
                        .HasForeignKey("CompanyCode", "VehicleId")
                        .HasPrincipalKey("CompanyCode", "Id")
                        .IsRequired()
                        .HasConstraintName("FK_DriverVehicles_Vehicle");

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Vms.Domain.Entity.Fleet", b =>
                {
                    b.HasOne("Vms.Domain.Entity.Company", "CompanyCodeNavigation")
                        .WithMany("Fleets")
                        .HasForeignKey("CompanyCode")
                        .IsRequired()
                        .HasConstraintName("FK_Fleet_Company");

                    b.Navigation("CompanyCodeNavigation");
                });

            modelBuilder.Entity("Vms.Domain.Entity.FleetNetwork", b =>
                {
                    b.HasOne("Vms.Domain.Entity.Fleet", "Fleet")
                        .WithMany("FleetNetworks")
                        .HasForeignKey("CompanyCode", "FleetCode")
                        .IsRequired()
                        .HasConstraintName("FK_FleetNetwork_Fleet");

                    b.HasOne("Vms.Domain.Entity.Network", "Network")
                        .WithMany("FleetNetworks")
                        .HasForeignKey("CompanyCode", "NetworkCode")
                        .IsRequired()
                        .HasConstraintName("FK_FleetNetwork_Network");

                    b.Navigation("Fleet");

                    b.Navigation("Network");
                });

            modelBuilder.Entity("Vms.Domain.Entity.Login", b =>
                {
                    b.HasOne("Vms.Domain.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vms.Domain.Entity.Network", b =>
                {
                    b.HasOne("Vms.Domain.Entity.Company", "CompanyCodeNavigation")
                        .WithMany("Networks")
                        .HasForeignKey("CompanyCode")
                        .IsRequired()
                        .HasConstraintName("FK_Network_Company");

                    b.Navigation("CompanyCodeNavigation");
                });

            modelBuilder.Entity("Vms.Domain.Entity.NetworkSupplier", b =>
                {
                    b.HasOne("Vms.Domain.Entity.Supplier", "Supplier")
                        .WithMany("NetworkSuppliers")
                        .HasForeignKey("SupplierCode")
                        .IsRequired()
                        .HasConstraintName("FK_NetworkSupplier_Supplier");

                    b.HasOne("Vms.Domain.Entity.Network", "Network")
                        .WithMany("NetworkSuppliers")
                        .HasForeignKey("CompanyCode", "NetworkCode")
                        .IsRequired()
                        .HasConstraintName("FK_NetworkSupplier_Network");

                    b.Navigation("Network");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Vms.Domain.Entity.RescheduleReason", b =>
                {
                    b.HasOne("Vms.Domain.Entity.Company", "Company")
                        .WithMany("RescheduleReasons")
                        .HasForeignKey("CompanyCode")
                        .IsRequired()
                        .HasConstraintName("FK_RescheduleReason_Company");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Vms.Domain.Entity.ServiceBookingEntity.ConfirmBookedRefusalReason", b =>
                {
                    b.HasOne("Vms.Domain.Entity.Company", "Company")
                        .WithMany("ConfirmBookedRefusalReasons")
                        .HasForeignKey("CompanyCode")
                        .IsRequired()
                        .HasConstraintName("FK_ConfirmBookedRefusalReason_Company");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Vms.Domain.Entity.ServiceBookingEntity.MotEvent", b =>
                {
                    b.HasOne("Vms.Domain.Entity.Vehicle", "Vehicle")
                        .WithMany("MotEvents")
                        .HasForeignKey("CompanyCode", "VehicleId")
                        .HasPrincipalKey("CompanyCode", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vms.Domain.Entity.ServiceBookingEntity.ServiceBooking", "ServiceBooking")
                        .WithOne("MotEvent")
                        .HasForeignKey("Vms.Domain.Entity.ServiceBookingEntity.MotEvent", "CompanyCode", "VehicleId", "ServiceBookingId")
                        .HasPrincipalKey("Vms.Domain.Entity.ServiceBookingEntity.ServiceBooking", "CompanyCode", "VehicleId", "Id");

                    b.Navigation("ServiceBooking");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Vms.Domain.Entity.ServiceBookingEntity.NonArrivalReason", b =>
                {
                    b.HasOne("Vms.Domain.Entity.Company", "Company")
                        .WithMany("NonArrivalReasons")
                        .HasForeignKey("CompanyCode")
                        .IsRequired()
                        .HasConstraintName("FK_NonArrivalReason_Company");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Vms.Domain.Entity.ServiceBookingEntity.NotCompleteReason", b =>
                {
                    b.HasOne("Vms.Domain.Entity.Company", "Company")
                        .WithMany("NotCompleteReasons")
                        .HasForeignKey("CompanyCode")
                        .IsRequired()
                        .HasConstraintName("FK_NotCompleteReason_Company");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Vms.Domain.Entity.ServiceBookingEntity.RefusalReason", b =>
                {
                    b.HasOne("Vms.Domain.Entity.Company", "Company")
                        .WithMany("RefusalReasons")
                        .HasForeignKey("CompanyCode")
                        .IsRequired()
                        .HasConstraintName("FK_RefusalReason_Company");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Vms.Domain.Entity.ServiceBookingEntity.ServiceBooking", b =>
                {
                    b.HasOne("Vms.Domain.Entity.User", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vms.Domain.Entity.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vms.Domain.Entity.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vms.Domain.Entity.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierCode");

                    b.HasOne("Vms.Domain.Entity.Vehicle", "Vehicle")
                        .WithMany("ServiceBookings")
                        .HasForeignKey("CompanyCode", "VehicleId")
                        .HasPrincipalKey("CompanyCode", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ServiceBookings_Vehicle");

                    b.Navigation("AssignedTo");

                    b.Navigation("CreatedBy");

                    b.Navigation("Owner");

                    b.Navigation("Supplier");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Vms.Domain.Entity.ServiceBookingEntity.ServiceBookingLock", b =>
                {
                    b.HasOne("Vms.Domain.Entity.ServiceBookingEntity.ServiceBooking", "ServiceBooking")
                        .WithOne("Lock")
                        .HasForeignKey("Vms.Domain.Entity.ServiceBookingEntity.ServiceBookingLock", "ServiceBookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceBooking");
                });

            modelBuilder.Entity("Vms.Domain.Entity.Supplier", b =>
                {
                    b.OwnsOne("Vms.Domain.Entity.Address", "Address", b1 =>
                        {
                            b1.Property<string>("SupplierCode")
                                .HasColumnType("varchar(8)");

                            b1.Property<string>("Locality")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("varchar(50)");

                            b1.Property<Geometry>("Location")
                                .IsRequired()
                                .HasColumnType("geography");

                            b1.Property<string>("Postcode")
                                .IsRequired()
                                .HasMaxLength(8)
                                .IsUnicode(false)
                                .HasColumnType("varchar(8)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("varchar(50)");

                            b1.Property<string>("Town")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("varchar(50)");

                            b1.HasKey("SupplierCode");

                            b1.ToTable("Supplier");

                            b1.WithOwner()
                                .HasForeignKey("SupplierCode");
                        });

                    b.OwnsMany("Vms.Domain.Entity.SupplierFranchise", "Franchises", b1 =>
                        {
                            b1.Property<string>("SupplierCode")
                                .HasColumnType("varchar(8)");

                            b1.Property<string>("Franchise")
                                .HasColumnType("varchar(30)");

                            b1.HasKey("SupplierCode", "Franchise");

                            b1.HasIndex("Franchise");

                            b1.ToTable("SupplierFranchise", (string)null);

                            b1.HasOne("Vms.Domain.Entity.VehicleMake", "Make")
                                .WithMany()
                                .HasForeignKey("Franchise")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner("Supplier")
                                .HasForeignKey("SupplierCode");

                            b1.Navigation("Make");

                            b1.Navigation("Supplier");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Franchises");
                });

            modelBuilder.Entity("Vms.Domain.Entity.Vehicle", b =>
                {
                    b.HasOne("Vms.Domain.Entity.Company", "CompanyCodeNavigation")
                        .WithMany("Vehicles")
                        .HasForeignKey("CompanyCode")
                        .IsRequired()
                        .HasConstraintName("FK_Vehicle_Company");

                    b.HasOne("Vms.Domain.Entity.Customer", "C")
                        .WithMany("Vehicles")
                        .HasForeignKey("CompanyCode", "CustomerCode")
                        .HasConstraintName("FK_Vehicle_Customer");

                    b.HasOne("Vms.Domain.Entity.Fleet", "Fleet")
                        .WithMany("Vehicles")
                        .HasForeignKey("CompanyCode", "FleetCode")
                        .HasConstraintName("FK_Vehicle_Fleet");

                    b.HasOne("Vms.Domain.Entity.VehicleModel", "M")
                        .WithMany("Vehicles")
                        .HasForeignKey("Make", "Model")
                        .IsRequired()
                        .HasConstraintName("FK_Vehicle_VehicleModel");

                    b.OwnsOne("Vms.Domain.Entity.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("VehicleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Locality")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("varchar(50)");

                            b1.Property<Geometry>("Location")
                                .IsRequired()
                                .HasColumnType("geography");

                            b1.Property<string>("Postcode")
                                .IsRequired()
                                .HasMaxLength(8)
                                .IsUnicode(false)
                                .HasColumnType("varchar(8)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("varchar(50)");

                            b1.Property<string>("Town")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("varchar(50)");

                            b1.HasKey("VehicleId");

                            b1.ToTable("Vehicle");

                            b1.WithOwner()
                                .HasForeignKey("VehicleId");
                        });

                    b.OwnsOne("Vms.Domain.Entity.VehicleMot", "Mot", b1 =>
                        {
                            b1.Property<Guid>("VehicleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("Due")
                                .HasColumnType("date");

                            b1.HasKey("VehicleId");

                            b1.ToTable("VehicleMot", (string)null);

                            b1.WithOwner("Vehicle")
                                .HasForeignKey("VehicleId")
                                .HasConstraintName("FK_Vehicle_VehicleMot");

                            b1.Navigation("Vehicle");
                        });

                    b.OwnsOne("Vms.Domain.Entity.VehicleVrm", "VehicleVrm", b1 =>
                        {
                            b1.Property<Guid>("VehicleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("ValidFrom")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("datetime2")
                                .HasColumnName("ValidFrom");

                            b1.Property<DateTime>("ValidTo")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("datetime2")
                                .HasColumnName("ValidTo");

                            b1.Property<string>("Vrm")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("nvarchar(12)");

                            b1.HasKey("VehicleId");

                            b1.ToTable("VehicleVrm", (string)null);

                            b1.ToTable(tb => tb.IsTemporal(ttb =>
                                    {
                                        ttb.UseHistoryTable("VehicleVrmHistory");
                                        ttb
                                            .HasPeriodStart("ValidFrom")
                                            .HasColumnName("ValidFrom");
                                        ttb
                                            .HasPeriodEnd("ValidTo")
                                            .HasColumnName("ValidTo");
                                    }));

                            b1.WithOwner("Vehicle")
                                .HasForeignKey("VehicleId")
                                .HasConstraintName("FK_Vehicle_VehicleVrm");

                            b1.Navigation("Vehicle");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("C");

                    b.Navigation("CompanyCodeNavigation");

                    b.Navigation("Fleet");

                    b.Navigation("M");

                    b.Navigation("Mot")
                        .IsRequired();

                    b.Navigation("VehicleVrm")
                        .IsRequired();
                });

            modelBuilder.Entity("Vms.Domain.Entity.VehicleModel", b =>
                {
                    b.HasOne("Vms.Domain.Entity.VehicleMake", "MakeNavigation")
                        .WithMany("VehicleModels")
                        .HasForeignKey("Make")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MakeNavigation");
                });

            modelBuilder.Entity("Vms.Domain.Entity.Company", b =>
                {
                    b.Navigation("ConfirmBookedRefusalReasons");

                    b.Navigation("Customers");

                    b.Navigation("Drivers");

                    b.Navigation("Fleets");

                    b.Navigation("Networks");

                    b.Navigation("NonArrivalReasons");

                    b.Navigation("NotCompleteReasons");

                    b.Navigation("RefusalReasons");

                    b.Navigation("RescheduleReasons");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Vms.Domain.Entity.Customer", b =>
                {
                    b.Navigation("CustomerNetworks");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Vms.Domain.Entity.Driver", b =>
                {
                    b.Navigation("DriverVehicles");
                });

            modelBuilder.Entity("Vms.Domain.Entity.Fleet", b =>
                {
                    b.Navigation("FleetNetworks");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Vms.Domain.Entity.Network", b =>
                {
                    b.Navigation("CustomerNetworks");

                    b.Navigation("FleetNetworks");

                    b.Navigation("NetworkSuppliers");
                });

            modelBuilder.Entity("Vms.Domain.Entity.ServiceBookingEntity.ServiceBooking", b =>
                {
                    b.Navigation("Lock");

                    b.Navigation("MotEvent");
                });

            modelBuilder.Entity("Vms.Domain.Entity.Supplier", b =>
                {
                    b.Navigation("NetworkSuppliers");
                });

            modelBuilder.Entity("Vms.Domain.Entity.Vehicle", b =>
                {
                    b.Navigation("DriverVehicles");

                    b.Navigation("MotEvents");

                    b.Navigation("ServiceBookings");
                });

            modelBuilder.Entity("Vms.Domain.Entity.VehicleMake", b =>
                {
                    b.Navigation("VehicleModels");
                });

            modelBuilder.Entity("Vms.Domain.Entity.VehicleModel", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
